#!/bin/bash

BRIGHTNESS=$(cat "$HOME/tmp/brightness") || 0
if [[ "$1" == "i" ]]; then
  ((++BRIGHTNESS))
elif [[ "$1" == "d" ]]; then
  ((--BRIGHTNESS))
fi

if [[ "$BRIGHTNESS" -gt 3 ]]; then
  $(rogauracore brightness 3)
  BRIGHTNESS=3
elif [[ "$BRIGHTNESS" -lt 0 ]]; then
  $(rogauracore brightness 0)
fi

$(rogauracore brightness $BRIGHTNESS)
exec echo $BRIGHTNESS > $HOME/tmp/brightness
