#!/bin/sh

# Makes aliases

#syscmd
alias \
	ls='ls --color=auto' \
	ll="ls -lha --color=auto --group-directories-first"

#Git
alias \
	gcheck="git checkout" \
	gc="git commit" \
	g="git"
	ga="git add"

alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

#nvim
alias \
    n="nvim"

#Share Screen
alias \
    ss="mon2cam --monitor 0 -f 30 -r 1920:1080 -s"\
    # ss="while true; do timeout 120s mon2cam --monitor 0 -f 30 -r 1920:1080 -s; sleep .3; done"\
    s="mon2cam --monitor 0 -f 30 -r 1920:1080"
    # s="while true; do timeout 120s mon2cam --monitor 0 -f 30 -r 1920:1080; sleep .3; done"
#Rust
alias \
    cn="cargo new" \
    cb="cargo build" \
    cr="cargo run"

##spicetify
alias \
   uspice="spicetify config extensions dribbblish.js
       spicetify config current_theme Dribbblish color_scheme custom
       spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
       spicetify apply"

#config
alias \
    evc="nvim ~/.config/nvim/init.vim"
    elc="nvim ~/texmf/tex/latex/beta/beta.sty"
    edc="nvim ~/.local/src/dwm/config.def.h"
    ebc="nvim ~/.local/src/dwmblocks/blocks.def.h"
