format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metric\
$cmd_duration\
$character\
"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = 'white bold'
style_root = 'white bold'
format = '[$user](bold blue)@'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold green) '
trim_at = '.companyname.com'
disabled = false

[directory]
truncation_length = 5

[git_branch]
symbol = ''
truncation_length = 4
truncation_symbol = ''
format = '[$symbol](purple) [$branch](purple) '

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[cmd_duration]
min_time = 500
format = 'took [$duration](bold cyan)'
